"""Add guacamole_password to Student model

Revision ID: 67ec12cc4f37
Revises: f164ccb09fe7
Create Date: 2025-11-13 19:12:04.445983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ec12cc4f37'
down_revision = 'f164ccb09fe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guacamole_password', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('guacamole_password')

    # ### end Alembic commands ###
