"""Add initial_password to Student

Revision ID: 719badf3f07c
Revises: abdc8e130003
Create Date: 2025-11-17 19:10:57.566860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719badf3f07c'
down_revision = 'abdc8e130003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('initial_password')

    # ### end Alembic commands ###
