"""Add NodeStorageConfig and VM.storage

Revision ID: 7ab9b15165d5
Revises: 9f3586f5eae0
Create Date: 2025-11-18 17:26:28.134138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab9b15165d5'
down_revision = '9f3586f5eae0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_storage_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('max_vms', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node_configurations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'name', name='uq_node_storage')
    )
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.drop_column('storage')

    op.drop_table('node_storage_configs')
    # ### end Alembic commands ###
