"""Add console_url to VirtualMachine

Revision ID: 818b25c84d91
Revises: 67ec12cc4f37
Create Date: 2025-11-17 04:18:50.425391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '818b25c84d91'
down_revision = '67ec12cc4f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('console_url', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.drop_column('console_url')

    # ### end Alembic commands ###
