"""Add storage_pools and rr index to NodeConfiguration

Revision ID: 9f3586f5eae0
Revises: c49eca35176b
Create Date: 2025-11-18 17:15:39.272681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3586f5eae0'
down_revision = 'c49eca35176b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_pools', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('storage_rr_index', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_configurations', schema=None) as batch_op:
        batch_op.drop_column('storage_rr_index')
        batch_op.drop_column('storage_pools')

    # ### end Alembic commands ###
