"""Add multi-node support with node configurations and template replication

Revision ID: c49eca35176b
Revises: 95b1a573ee09
Create Date: 2025-11-18 17:11:28.359599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49eca35176b'
down_revision = '95b1a573ee09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=120), nullable=False),
    sa.Column('max_vms', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('storage_pool', sa.String(length=120), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_name')
    )
    op.create_table('vm_template_replicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('target_node', sa.String(length=120), nullable=False),
    sa.Column('proxmox_template_id', sa.Integer(), nullable=False),
    sa.Column('is_ready', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['vm_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'target_node')
    )
    with op.batch_alter_table('vm_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replicate_to_all_nodes', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_templates', schema=None) as batch_op:
        batch_op.drop_column('replicate_to_all_nodes')

    op.drop_table('vm_template_replicas')
    op.drop_table('node_configurations')
    # ### end Alembic commands ###
