"""Fix VM uniqueness constraint to composite node+vmid

Revision ID: f2790feb1350
Revises: d1f2g3h4i5j6
Create Date: 2025-12-15 18:25:38.551734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2790feb1350'
down_revision = 'd1f2g3h4i5j6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite batch mode will recreate the table, automatically removing the old UNIQUE constraint
    with op.batch_alter_table('virtual_machines', schema=None, recreate='always') as batch_op:
        batch_op.alter_column('proxmox_vmid',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('proxmox_node',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        
        # Add the new composite unique constraint  
        batch_op.create_unique_constraint('uq_node_vmid', ['proxmox_node', 'proxmox_vmid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('virtual_machines', schema=None) as batch_op:
        batch_op.drop_constraint('uq_node_vmid', type_='unique')
        batch_op.alter_column('proxmox_node',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('proxmox_vmid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
